version: '3.7'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: '2.7.2'
        PG_MAJOR: '12.6'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.5'
        BUNDLER_VERSION: '2.1.4'
    image: example-dev:1.0.1
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - .dockerdev/bundle:/bundle
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
    depends_on:
      - postgres
      - redis
      - imgproxy

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:12.6
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - ./log:/root/log:cached
      - postgres:/var/lib/postgresql/data
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres

  redis:
    image: redis:6.0-alpine3.13
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    environment:
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}
      - IMGPROXY_ENDPOINT=${IMGPROXY_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - IMGPROXY_USE_S3=${IMGPROXY_USE_S3}
    ports:
      - '8080:8080'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules
      - .dockerdev/bundle:/bundle
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  postgres:
  redis:
  node_modules:
  rails_cache:
  packs:
