env:
  PROJECT_NAMESPACE: melobeem
  ECR_PATH: ${{ secrets.AWS_REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com

name: Manual deploy production
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repositroy
        uses: actions/checkout@v2

      - name: Build Image
        run: docker build -t ${{ env.PROJECT_NAMESPACE }}:${{ github.sha }} .

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: ${{ env.PROJECT_NAMESPACE }}:${{ github.sha }}

      - name: Pull code from ECR to EC2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: export IMAGE=${{ env.ECR_PATH }}/${{ env.PROJECT_NAMESPACE }}:${{ github.sha }} && cd deploy/melobeem && ./ecrdeploy.sh
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.EC2_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
